- .gitignore
- index.ios.js
- ios/ForestWatcher.xcodeproj/project.pbxproj
- ios/ForestWatcher.xcworkspace/contents.xcworkspacedata
- ios/ForestWatcher/AppDelegate.m
- ios/Podfile
- ios/Podfile.lock
- package.json
- Map component implementation
- Cocoa Pods instructions:
- Install cocoapods -> https://cocoapods.org/
- Go to ios/ and run `pod install`
To-do: Add Google maps keys when we add the environment configuration.
> Feat: Basic map

- android/app/build.gradle
- android/app/src/main/java/com/forestwatcher/MainActivity.java
- android/app/src/main/res/values/strings.xml
- android/settings.gradle
- app/components/app/index.js
- app/components/dashboard/index.js
- app/components/dashboard/styles.js
- app/components/map/index.js
- app/components/map/styles.js
- app/containers/dashboard/index.js
- app/locales/en.js
- app/locales/es.js
- app/locales/fr.js
- app/locales/index.js
- app/redux-modules/navigation.js
- app/routes/index.js
- ios/ForestWatcher.xcodeproj/project.pbxproj
- package.json
- Added `react-native-i18n` to manage translations.
- Removed deprecated attribute (Key) from the `NavigationCardStack` state.
- Added two basic new views, dashboard and map.
> Feat: i18n and Navigation fixes

- app/components/app/index.js
- app/components/common/header/index.js
- app/components/common/header/styles.js
- app/components/dashboard/index.js
- app/components/dashboard/styles.js
- app/components/map/index.js
- app/components/map/styles.js
- app/containers/common/header/index.js
- app/containers/dashboard/index.js
- app/redux-modules/navigation.js
- Added the header component inside the `NavigationCardStack`
- Added an action to hide / show the header
- [Platform specific styles](https://facebook.github.io/react-native/docs/platform-specific-code.html) for the header
- Added loader before rendering the map to get a smooth transition between views.
> Feature: Navigation header and map improvements

- android/app/build.gradle
- android/app/src/main/java/com/forestwatcher/MainApplication.java
- android/settings.gradle
Manual linking of `react-native-maps`
We can't use the auto linking of react-native (react-native link) because it's not compatible with the PodFile
> Feat: Android - Manual link of react-native-maps

- android/app/src/main/java/com/forestwatcher/MainActivity.java
- android/app/src/main/java/com/forestwatcher/MainApplication.java
Manual Android package link for `react-native-i18n`
> Fix: Android - React Native i18n Link

- app/components/setup/country/index.js
- app/config/constants/index.js
- app/helpers/language.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/redux-modules/countries.js
- Added a new language helper
- Countries fixes, removed the column name from the translations and moved it to the `CONSTANTS` file
> Feat: Countries changes and language helper

- app/components/common/search-selector/index.js
- app/components/common/search-selector/styles.js
- app/redux-modules/countries.js
- Updated query to show data without empty names
- Updated styles
> Fix: Country selector - updated query and styles

- app/components/common/list/index.js
- app/components/common/list/styles.js
Add list component:
- Styles
- Logic
We can make different list now sent and object to the component.
> Add styles and logic to component list

- app/components/alerts/list/index.js
- app/components/common/header/index.js
- app/components/login/index.js
- app/components/settings/index.js
- app/components/setup/boundaries/index.js
- app/components/setup/country/index.js
- app/components/setup/draw-areas/index.js
- app/components/setup/header/index.js
- app/components/setup/index.js
- app/components/setup/overview/index.js
- app/components/setup/protected-areas/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
Add new texts in the following components:
- Alert list.
- Header.
- Login.
- Boundaries.
- Draw Areas.
- Header (setup).
- Index (setup).
- Overview (setup).
- Protected Areas (setup)
> Add new texts for transifex traductions

- android/app/src/main/AndroidManifest.xml
- app/components/setup/overview/index.js
- app/components/setup/overview/styles.js
Fix input position on Android and IOS.
> Fix input position when keyboard is open

- app/components/common/list/index.js
- app/components/common/list/styles.js
- app/components/settings/index.js
- Update list component
- Update about view with list component
> Update about view with list component and improve it

- app/components/common/search-selector/styles.js
Now the area where user can touch is bigger.
***pink color is the area.**
> Fix placeholder click area on country searcher

- app/components/setup/overview/index.js
- app/components/setup/overview/styles.js
- package.json
Disabled scroll on image container
> Fix keyboard error on IOS

- app/components/dashboard/index.js
- app/components/dashboard/styles.js
> Home styes

- app/components/login/index.js
- app/containers/login/index.js
- app/locales/en.json
There is a bug when there was no internet connection so this PR checks the connection before login and shows an alert when offline.
> Check connection in login

- app/components/alerts/list/index.js
- app/components/common/image-cache/index.js
- app/components/feedback/index.js
- app/components/map/index.js
- app/components/reports/new/index.js
- app/components/setup/overview/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/index.js
- app/locales/pt.json
Added new translations and missing strings.
> Language review

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/forestwatcher/MainApplication.java
- android/settings.gradle
- app/components/map/index.js
Remove unused library for android
> Remove unsused library

- app/config/constants/index.js
- app/redux-modules/countries.js
Fixes the setup when using the app for the first time in a language different than english
> Fix: Setup breaking because of missing constants

- app/components/alerts/list/index.js
- app/components/common/form-inputs/date/index.js
- app/components/common/image-cache/index.js
- app/components/map/index.js
> Fixes locales strings

- app/locales/reports/FW-report-FR.json
> Add french report

- app/components/feedback/form.js
- app/containers/feedback/form.js
Gets the feedback from by the language
> Fix: Feedback form by language

- app/containers/feedback/form.js
Fix the daily / weekly feedback language.
> Fix feedback language

- android/app/src/main/AndroidManifest.xml
- app/components/alerts/index.js
- app/components/alerts/list/index.js
- app/components/common/form-inputs/blob/index.js
- app/components/common/form-inputs/blob/styles.js
- app/components/common/image-cache/index.js
- app/components/home/index.js
- app/components/map/index.js
- app/components/reports/new/form.js
- app/components/reports/new/next-button/styles.js
- app/components/setup/boundaries/index.js
- app/components/setup/draw-areas/index.js
- app/components/setup/protected-areas/index.js
- app/containers/alerts/index.js
- app/containers/alerts/list/index.js
- app/containers/home/index.js
- app/containers/setup/boundaries/index.js
- app/helpers/fileManagement.js
- app/redux-modules/alerts.js
- app/redux-modules/areas.js
- app/redux-modules/geostore.js
- app/redux-modules/index.js
- package.json
- Intersection of geojson and map improvements
- LargeHeap to fix outofmemory
- Fix fit to coordinates
- Get report and feedback questions on load
- Try camera button out of camera component
- Fix storing of reports on load
- File helper changes and form picture input improvements
- Camera styles
- Fix image height
- Resize mode in image cache
**DO NOT MERGE YET**: We need to figure out the issue with `turf-intersect` and the updated version its using of a package that is not compatible with react native.
> Feat: Intersection of GeoJSON and Android improvements

- app/redux-modules/areas.js
- Change post to form-date
- Add image in the form
The image seems very big!
> Change post images to form-data and add image

- app/components/map/styles.js
- app/components/setup/overview/index.js
- app/locales/en.json
Added saving state to avoid multiple taps
> Feat: Disabled state when saving area

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- app/components/common/form-inputs/blob/index.js
- app/components/common/form-inputs/blob/styles.js
- app/components/map/styles.js
- Add loading when saving and prevent from taking other pictures
- Changed build version
> Fix: Camera

- app/components/alerts/list/index.js
- app/components/common/image-cache/index.js
- app/containers/common/image-cache/index.js
- app/helpers/fileManagement.js
- app/locales/en.json
Temp fix while we remove this screen
> Temp fix for images

- android/build.gradle
- app/components/settings/index.js
- app/components/settings/styles.js
- app/containers/settings/index.js
- app/redux-modules/areas.js
- package.json
- New `Time-Frame` section in the Settings view that reads min/max dates.
- New action in the Areas store module.
- New react-native dependency: DatePicker component (`react-native-datepicker`)
> Feat: areas settings dates

- app/components/map/index.js
- app/components/map/styles.js
Added bounds while switching between AOI and some styles to the tabs
> Feat: Map - Styles for tabs and bounds for AOI

- app/redux-modules/areas.js
The images were not being passed through the reducer action
> Pass images from reducer action

- app/components/map/styles.js
- app/components/settings/area-detail/index.js
- app/components/settings/area-list/index.js
- app/components/settings/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
Missing translations and cleaning code
> Translations and cleaning

- android/build.gradle
- app/components/map/index.js
Show the selected alert in the native canvas layer depending on the zoom level.
TODO: improve the accuracy of the point.
Don't forget to update the npm dependencies.
> Show selected tile in the tile layer

- app/components/common/form/form-step.js
- app/containers/common/form/index.js
- app/redux-modules/feedback.js
- app/redux-modules/reports.js
Allow storing reports when offline
> Fix: Reports offline

- app/components/setup/draw-areas/index.js
- app/config/constants/index.js
Check shape size when the user undos a point and increased the max total area to `1500km2`
> Fix: Check shape size and increased the total area size

- app/components/map/index.js
- app/redux-modules/reports.js
Send user selected lat long instead of the GPS and fix the user data sent in the form
> Fix: Report - Selected position and user data

- app/locales/id.json
> Translations

- app/components/common/form-inputs/blob/index.js
- package.json
Camera fixes and support for devices with only front cameras. This also updates the camera library.
To-do -> Add translations for the permissions popup for newer devices
> Fix: Camera improvements

- app/components/common/form-inputs/select/index.js
- app/locales/reports/FW-report-EN.json
- app/locales/reports/FW-report-ES.json
- app/locales/reports/FW-report-FR.json
- app/locales/reports/FW-report-ID.json
- app/locales/reports/FW-report-PT.json
- Updates for the reports adding one more conditional
- Support for more than one child conditional for select inputs
*Update your .ENV IDs*:
```
QUESTIONNARIE_ID_EN=5919dddba1bd4d000bc90190
QUESTIONNARIE_ID_ES=5919deefa1bd4d000bc901b2
QUESTIONNARIE_ID_FR=5919dfb0a1bd4d000bc901d4
QUESTIONNARIE_ID_ID=5919e07ba1bd4d000bc901f6
QUESTIONNARIE_ID_PT=5919e122a1bd4d000bc90219
```
> Fix: Forms support for multiple child conditionals and reports update

- app/components/map/index.js
- package.json
This PR add the following:
- Includes a line in the between the user's location & the selected alert when the device has no compass.
- Add throttle to the map, map carousel and the location event handler.
**Todo**
> Feat: compass line fallback

- app/components/map/index.js
Carousel was not working and going into a loop
> Updating the selected area needs the next index, not the present one

- app/redux-modules/user.js
Remove the google permissions for the app on logout so after it you can signin again with a new account.
> Google signout

- app/main.js
- app/offline/detectNetwork.js
- app/offline/index.js
- app/offline/middleware.js
- app/redux-modules/app.js
- Adds custom detect network handler to redux-offline to support not only `isConnected` but also `isConnectionExpensive` and network `reach` store props.
> Feat: offline detect network enhancements

- app/components/common/form-inputs/check-btn/index.js
- app/components/common/form-inputs/radio/index.js
- app/components/common/form-inputs/select/index.js
- app/components/settings/area-detail/alert-system/dataset-options/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- package-lock.json
Change the offline switch to a new checkbox input.
I know, I know the styles aren't good but let's fix all them later with the styles review.
> Move offline switch to checkbox

- app/components/common/action-button/index.js
- app/components/common/action-button/styles.js
- app/components/home/index.js
- app/components/home/styles.js
- app/components/login/index.js
- app/components/sync/index.js
- app/components/sync/styles.js
- app/config/constants/index.js
- app/config/oAuth/GoogleOAuth.js
- app/containers/home/index.js
- app/containers/login/index.js
- app/containers/sync/index.js
- app/helpers/sync.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/alerts.js
- app/redux-modules/app.js
- app/redux-modules/areas.js
- app/redux-modules/countries.js
- app/redux-modules/feedback.js
- app/redux-modules/geostore.js
- app/redux-modules/reports.js
- app/redux-modules/user.js
- app/screens/index.js
> Feat: syncing page

- app/config/theme/index.js
> Fix deleted color

- app/components/setup/draw-areas/index.js
- app/components/sync/index.js
- package.json
- Uses react-native-timer to implement timeouts. This addresses the issue where timeouts are called after a component was unmounted. **More info:** https://facebook.github.io/react-native/docs/timers.html#timermixin
Needs running:
> npm i
> feat: uses react-native-timer implementation of setTimeout

- app/helpers/area.js
- package-lock.json
We were looking for layers inside the coverage object but the array of layers is inside `layers` attribute so this fix it and set the default glad timeframe in 6 months
> Fix glad layer when available and timeframe

- android/build.gradle
No more build tools for project dependencies 🎉
This will black magic  🔮  will build all of them for us thanks to @geriux !
> Build subprojects automagically on project build

- app/components/dashboard/index.js
- app/components/home/index.js
- app/containers/home/index.js
- app/containers/sync/index.js
- app/helpers/sync.js
- app/redux-modules/areas.js
- app/redux-modules/countries.js
- package-lock.json
This PR fix the multiple sync screens opening bug.
In the actionsPending we weren't taking into account the actionsInProgress so this PR includes both checks and now we remove the intermediate states.
Also include rollback for getCountries action.
> Remove intermediate states for syncing

- app/locales/templates/FW-daily-feedback.json
- app/locales/templates/FW-report.json
- app/locales/templates/FW-weekly-feedback.json
Small PR to update the local Report Templates for the default public reports to handle multi-language and correct API validation on the new endpoints /reports:
- FW Report: the default report for all areas, now public and accessible to all users
- FW Daily Feedback: the same as before but english and spanish in a single report
- FW Weekly Feedback: as above
> Feature: merge report templates JSON to multi-language

- app/components/map/area-carousel/index.js
- app/components/map/area-carousel/styles.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/areas.js
- New text in the areas carousel that specifies when was the dataset last updated.
> Feat:areas last updated

- app/components/map/index.js
- app/containers/map/index.js
- app/containers/reports/form.js
- app/redux-modules/alerts.js
This PR fixes an issue that occurred when making a report with GLAD points. Now the points are removed when leaving the map so the performance doesn't diminish.
> fix: adds flag to hide/display alerts on the map

- app/components/map/index.js
This PR makes the report available even when there isn't an alert.
> Make the report available when no alert

- app/components/common/form/answer/answer.js
- app/components/common/form/answers.js
- app/components/common/form/styles.js
- app/components/reports/index.js
- app/containers/common/form/answers.js
- app/containers/reports/index.js
- New button on the reports list to review your submitted answers.
- Removes upload report button from the _finished but not uploaded_ reports, because now when the connection is back redux-offline will upload them automagically.
> Feat: review uploaded

- app/components/common/form/form-step.js
- app/components/error-lightbox/index.js
- app/containers/common/form/form-step.js
- app/helpers/forms.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/main.js
- app/redux-modules/feedback.js
- app/redux-modules/reports.js
- app/screens/index.js
This PR addresses the following issue:
- Due to some changes on the API the forms were not being saved.
- When there were no forms the reporting crashed.
- Adds error notification component `ErrorLightbox`.
> Fix: form component crashing

- app/containers/map/index.js
- app/redux-modules/app.js
- app/redux-modules/reports.js
This feature syncs the custom report templates for each area in case that it has one.
> Sync custom area templates

- app/components/map/index.js
- ios/Podfile.lock
- package-lock.json
Moving getMapZoom to a pure function passing the region as param address to get the last zoom on region change and reset when zoom out.
> Remove alerts selected on zoomout

- app/components/common/action-card/index.js
- app/components/common/action-card/styles.js
- app/components/common/form/answers.js
- app/components/common/image-card/index.js
- app/components/common/image-carousel/index.js
- Add picture button is displayed if the image is not taken.
> feat: add-images-button

- app/components/common/action-card/index.js
- app/components/common/form-inputs/blob/index.js
- app/components/common/form/answers.js
- app/components/common/image-carousel/index.js
- app/helpers/forms.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/user.js
- Prevents sync page appearing on logout.
- Reads template status instead of report status.
- Prevents edit picture if readOnly
- Image not passed to getAction.
- Show camera on iOS.
> Fix: bugs you gotta catchem all

- android/app/build.gradle
- android/app/src/main/java/com/forestwatcher/MainApplication.java
- android/settings.gradle
- app/components/common/action-card/index.js
- app/components/common/form-inputs/blob/index.js
- app/components/common/form/answers.js
- app/components/common/form/form-step.js
- app/components/common/image-carousel/index.js
- app/containers/common/form/form-step.js
- app/helpers/forms.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- ios/ForestWatcher.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- Replaces old camera lib with `react-native-image-picker`.
- With these changes the camera becomes more responsive, faster and easier to deal with.
- Adds the possibility to choose pictures from the photo library.
- Prevents form submission w/ a required picture is missing.
> Feat: camera improvements

- app/components/sync/sync-progress/index.js
- app/components/sync/sync-progress/styles.js
- app/offline/effect.js
- app/redux-modules/app.js
- app/redux-modules/countries.js
- app/redux-modules/layers.js
- app/redux-modules/user.js
- package-lock.json
- Fix issue where cache rollback was not being dispatched because the RNFetchBlob was not rejecting the promises
> Fix: sync takes too long

- app/containers/reports/index.js
- Sorts created reports to be order by most recent first in every section.
> feat: sorts reports by most recent

- app/redux-modules/user.js
- Dispatches redux-offline RESET_STATE on logout to clean the outbox.
> feat: reset-offline-outbox-on-logout

- app/components/map/index.js
- app/components/settings/index.js
- app/containers/settings/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/reports.js
This PR addresses the following:
- User position was not being saved properly nor in the expected format by the API.
[Bonus]
- Prevents adding areas if no internet connection
> fix: user postion + clicked position format

- CHANGELOG.md
- android/app/build.gradle
- ios/ForestWatcher/Info.plist
- package.json
See changelog for more details.
> Release 1.0.0.rc4

- app/redux-modules/layers.js
- app/redux-modules/reports.js
- Includes report name in the report upload.
- Fixes issue that happened when opening the app with no AoI. The sync never finished because Layers depended on Areas and Areas depended on finishing the sync.
> Fix: setup not showing

- app/components/common/area-list/area-cache/index.js
- app/components/common/row/index.js
- app/components/reports/index.js
- app/components/reports/styles.js
- app/components/setup/draw-areas/index.js
- app/redux-modules/alerts.js
- app/redux-modules/areas.js
- Extends Row to receive a rowStyle prop, in order to support complex tweaks.
- Includes Row component in the Reports List:
- Before to access a report the user had to click on the action icon, which felt awkward and caused confusion.
- Now to access a report clicking in the row will do the trick. 🎉 
Long live the `<Row />`!
> Fix: kinda cant click submited report

- app/components/common/action-card/index.js
- app/components/common/area-list/area-cache/index.js
- app/components/common/form/answers.js
- app/components/common/form/styles.js
- app/components/common/image-carousel/index.js
- app/components/common/row/index.js
- app/components/reports/index.js
- app/components/reports/styles.js
- app/components/setup/draw-areas/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/alerts.js
- app/redux-modules/areas.js
- Updates locales and adds missing texts.
- Removes scroll from `ImageCarousel` when there's only image.
- Correctly centers image.
- Removes annoying `HorizontalScrollIndicator` when +1 images.
- Changes color of `ActionCard` text to match theme.
> Fix: answers image carousel

- app/containers/common/form/answers.js
- app/containers/common/form/form-step.js
- app/containers/reports/form.js
- app/containers/reports/index.js
- app/helpers/forms.js
- app/redux-modules/reports.js
- fixes answers post endpoint 🙄  .
- uses getTemplate as source of truth for template related stuff across the app.
> fix: report-submission-custom-templates

- app/components/reports/index.js
- app/offline/effect.js
- app/redux-modules/reports.js
- Possibility to arbitrarily set errorCode on url effects.
- Changes to request of reports upload to be optimist about the upload.
- Changes to rollback of reports upload to display an upload button.
> Fix: report upload rollback button

- CHANGELOG.md
- android/app/build.gradle
- ios/ForestWatcher/Info.plist
- package.json
> RC5 release

- app/components/setup/draw-areas/index.js
Fixed:
- Errors on polygons and dots (when you delete the dots, now the line also disappear)
- Improve fitbounds and render map functions.
> Fix polygon error on map and improve map functions

- app/components/common/action-button/styles.js
> Fix center text on buttons

- app/components/common/action-button/index.js
- app/components/common/dropdown/index.js
- app/components/common/dropdown/styles.js
- app/components/common/list/styles.js
- app/components/dashboard/index.js
- app/components/dashboard/styles.js
- app/components/settings/area-detail/alert-system/index.js
- app/components/settings/area-detail/alert-system/styles.js
- FIx some text and buttons styles.
> Fix text styles

- app/components/walkthrough/index.js
- Adds missing support for sliding in the walkthrough page.
> fix: adds event handler to support sliding on walkthrough

- app/components/map/index.js
- app/components/setup/boundaries/index.js
- app/components/setup/draw-areas/index.js
- app/components/setup/header/index.js
- app/components/setup/header/styles.js
- app/components/setup/index.js
- app/containers/map/index.js
- app/containers/setup/boundaries/index.js
- app/helpers/map.js
This PR include:
- Contextual layers on Draw Map view.
> Include contextuals layers on set up map

- app/components/map-sidebar/index.js
- app/components/setup/header/index.js
- app/components/setup/header/styles.js
- app/components/setup/index.js
- app/components/walkthrough/index.js
- app/components/walkthrough/styles.js
- app/containers/map-sidebar/index.js
- app/containers/right-drawer/index.js
- app/containers/setup/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- app/redux-modules/app.js
- app/redux-modules/layers.js
This PR addresses the following issues:
- Adds map sidebar missing scroll.
- Adds possibility to slide to the login screen from the walkthrough.
- Adds possibility to log out from setup when user has no areas.
- Adds skip button to walkthrough.
> Fix: quick bug fixes

- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
Small text changes asked by Liz.
> Fixes description for About page

- app/components/home/index.js
- app/components/home/styles.js
- app/components/sync/styles.js
This PR stops issue where app got stuck on infinite spinner, because modalOpen was rehydrated and modal never opened again.
> fix: infinite spinner

- android/app/src/main/AndroidManifest.xml
- app/components/settings/faq/index.js
- app/components/walkthrough/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- Updates android manifest to make camera an optional feature.
- Updates locales.
- Fixes walkthrough textOnly styles.
- Fixes regression on slide to login feature.
- Don't show empty questions.
> Feat: texts and manifest update

- CHANGELOG.md
- app/config/constants/index.js
- app/config/oAuth/GoogleOAuth.js
- app/redux-modules/user.js
- package-lock.json
- Removes logout action from `redux-offline` flow.
- Uses `signOut` method instead of `revokeAccess`.
- Prevents showing error when user dismisses logout dialog.
> fix: logout-throws-error-sometimes

- app/locales/templates/FW-questionnaire.json
A reference template for the default questionnaire translations in Forest Watcher as backup for the api.
> Feature/ create template for FW questionnaire translations

- app/components/common/form-inputs/radio/index.js
- app/components/setup/index.js
- app/components/setup/overview/index.js
- Scroll is not available in single selection questions.
- Keyboard blocks the text input when creating an area.
> Fix: inputs scroll view

- app/offline/effect.js
- app/redux-modules/layers.js
Removes last promise type effects and removes promise logic from effect
> fix: removes promise effect because promises are not serializable

- android/build.gradle
- app/components/toast-notification/index.js
- app/components/toast-notification/with-notifications.js
- app/helpers/forms.js
- app/redux-modules/reports.js
- app/types/areas.types.js
- app/types/form.types.js
- app/types/reports.types.js
- app/types/store.types.js
- ios/ForestWatcher.xcodeproj/project.pbxproj
- ios/ForestWatcher.xcodeproj/xcshareddata/xcschemes/ForestWatcher.xcscheme
This PR adds flow types to the reports and form reducers.
Also adds a delay of 15s to the error notifications.
> feat: adds flow type to reports and forms

- app/components/setup/country/index.js
- app/redux-modules/countries.js
- app/types/setup.types.js
Prevent showing countries without centroid
> Fix: prevent showing countries without centroid

- app/components/map/index.js
- app/components/setup/draw-areas/index.js
- Uses mapbox in `<DrawArea />`
> fix: replace google basemap with mapbox in area create

- app/components/login/index.js
- app/components/login/styles.js
- app/redux-modules/user.js
- ios/ForestWatcher/Info.plist
- Updates FB login config to use GFW API account.
- Fixes login dismiss error.
- Fixes login layout in Android.
> Fix: login fb layout issues

- .eslintrc.yml
- app/components/map/clusters/clusterMarker.js
- app/components/map/clusters/index.js
- app/components/map/clusters/styles.js
- app/components/map/index.js
- app/components/map/styles.js
- package-lock.json
- package.json
- Resize markers when exceeding certain zoom level.
- Changes styles of neighbour markers to make it clearer.
- Changes styles of selected marker to correspond neighbours.
> Feat: markers resize on zoom

- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
With transifex updated is easy to handle translations... this PR just pull the new strings.
> Pull translations from transifex

- android/app/src/main/AndroidManifest.xml
Add compass needs to mobile device specifications on play store.
> Include compass uses for play stores

- app/components/settings/index.js
- app/components/settings/styles.js
- app/locales/en.json
- app/redux-modules/reports.js
- app/redux-modules/user.js
- app/sagas/app.js
This comes from the request of including the name in the FWD desktop reports page.
So now a link to my_gfw section appears when you haven't fill it yet.
> Show link to complete my gfw profile when empty
