Vizzuality/forest-watcher

- app/components/setup/draw-areas/index.js
- app/components/setup/protected-areas/index.js
- app/helpers/fileManagement.js
Fixes the storing of images for android, `file` was missing from the URL. This is not needed for iOS.
Added a new helper to parse an URL before storing, if it's on Android it will add file:// before the path.
> Fix: Snapshot image store for android

- app/components/reports/index.js
To avoid crashes check if the param is a function before triggering it.
> Check is function before onPress

- app/components/map/index.js
- app/redux-modules/alerts.js
If the user has Peru as a country the map won't use the 60 alerts limit.
Remember to change it in your user profile.
> Remove limit points for Peru

- app/components/common/form-inputs/blob/index.js
- package.json
As the new version is breaking in some android devices I've done a rollback of that change.
Remember to run `npm install`
> Rollback camera update

- app/components/connectionstatus/index.js
The connected component in the dashboard was being unmounted just after mounting with the new navigation system
> Remove willUnmount from connection status

- app/components/common/form/index.js
- app/components/reports/form.js
- app/containers/common/form/form-step.js
- app/containers/reports/form.js
- app/redux-modules/reports.js
- app/screens/index.js
- On save draft resets to root instead of popping current view.
> Fix: form save reset

- app/components/map/index.js
- app/redux-modules/areas.js
The map was crashing because it wasn't returning to the first area when one area was deleted (and the area of the selected index was deleted)
Extra: Fix delete alerts before fetching. Clean of db for an areaId and slug
> Return the selectedIndex to the prev area when one area is deleted

- app/components/settings/index.js
We check the props to redirect to setup page after we delete the last area
> Redirect to setup if there are no areas

- app/locales/en.json
Update partners text from:
partners->description: "Forest Watcher 2.0 is supported by a partnership of organizations contributing data, technology, funding and expertise"
partners->listOfPartners: "See a full list of partners below"
To:
partners->description: "Forest Watcher is created in collaboration between World Resources Institute, Vizzuality, and the Jane Goodall Institute"
partners->listOfPartners: "See all Global Forest Watch partners"
> Fix: update partners text (english)

- app/components/map/index.js
- app/components/setup/draw-areas/index.js
Setting a timeout to render the map in draw-areas fix the first draw area point and also was included in the map to improve performance as is not rendering everything at the same time with the clusters.
> Fix first point in area creation draw

- app/components/dashboard/index.js
- app/components/home/index.js
- app/components/map/index.js
- app/components/setup/index.js
- app/components/sync/index.js
- app/containers/dashboard/index.js
- app/containers/home/index.js
- app/containers/map/index.js
- app/containers/sync/index.js
- app/redux-modules/app.js
- app/redux-modules/areas.js
The skip button saves a flag in the state until the app is open again so we don't show the sync modal every time that we navigate between screens. It is hidden if we don't have the areas synced as they are necessary for the app.
Also, when we press on the sync in 3G shows the sync loading spinner.
> Fix skip and only it when has alerts

- app/redux-modules/areas.js
This PR removes the alerts stored in the database to avoid duplicated entries.
> Reset db on logout to remove old alerts

- app/components/settings/area-detail/index.js
- Adds keyboardShouldPersistTaps prop to area-detail ScrollView to avoid having to double tap to perform an action. This issue occurred because the `TextInput` component had the focus thus tapping once removed the focus and tapping again performed the action.
> NOTE: This issue still needs to be resolved in the `SearchSelector` and the `Overview` components. This solution wasn't viable in these components because the input is not child of a `ScrollView` like in the `AreaDetail` component. Will address these issues in the future.
> fix: prevent-double-press-on-area-detail

- app/components/setup/draw-areas/index.js
- Fit bounds of the create area map on clicking next. This ensures that the area picture is always centered. 🗺  📸  💪
> feat: adds fit bounds to area map before the screenshot

- app/components/map/area-carousel/index.js
- app/components/map/area-carousel/styles.js
- app/components/map/index.js
- app/components/map/styles.js
- app/components/settings/area-detail/index.js
- app/components/settings/area-detail/styles.js
- On the area-detail page, makes the area image occupy the whole width of the image container.
- On the map:
- When an alert is selected hide the carousel and show the coordinates on the nav header. Also, display distance texts on top of the report button. When the alert is deselected restore the nav header title.
- Improves deselect of alerts.
> Fix: area-detail + map carousel styles polishing

- app/main.js
- app/offline/index.js
- app/redux-modules/app.js
- package.json
- On app init, the `package.json` version is compared with the persisted store version. If the two don't match, the persisted store is purged.
**[BONUS]**
- Makes the app portrait only.
> Feat: invalidate redux persist

- app/components/settings/area-detail/alert-system/dataset-options/index.js
- app/components/settings/area-detail/alert-system/index.js
- app/containers/settings/area-detail/alert-system.js
- app/helpers/area.js
- app/redux-modules/areas.js
- Removes `setAreaDatasetCache` action from redux-module, container and components, because now cache is always true.
- Fixes an issue that prevented from changing alerts timeframe. This was due to a mutation of the dataset object included in the area object. ✌️
> fix: removes unused action + prevents area dataset mutation

- app/components/common/area-list/area-cache/index.js
- app/containers/dashboard/area-cache.js
- app/redux-modules/geostore.js
- app/redux-modules/layers.js
This PR includes the following changes:
- Shows progress bar indeterminate state until % > 0.
- Removes area from layersProgress on rollback to prevent showing misleading progress.
- Avoid showing cache error message until all layers have been processed.
> Fix: download progress retry issues

- app/components/common/area-list/area-cache/index.js
- app/components/setup/draw-areas/index.js
- app/redux-modules/alerts.js
- Adds default props to AreaCache to prevent crash when cacheStatus is empty.
- Changes snapshot format from `.png` to `.jpg` to prevent crash on area creation.
- Resets alerts pendingData and syncError on app start.
> Fix: creating areas crash

- app/components/common/area-list/area-cache/index.js
- app/components/setup/draw-areas/index.js
- app/redux-modules/alerts.js
- app/redux-modules/areas.js
This PR includes: 
- Fix not all area images downloaded correctly. Every time that a new `pendingData.coverage` key was added, all the existing `pendingData.image` keys were being deleted.
- Changes check for existence from the area list to the image dictionary, for coherence.
> Fix: images not saved properly

- app/components/common/area-list/index.js
- app/components/dashboard/index.js
- app/redux-modules/layers.js
This PR addresses the following:
- Disables cache functionality on iOS
- Issue introduced in (5197f596007358d9dd248d6262c6eeeb777fb60e) that showed the downloaded button when a download failed partially and the last layer was a success.
- Improvement in `layersProgress` logic that sets:
- progress = 1 on commit
- progress = 0 on rollback
> Fix: done button not showing

- app/components/common/area-list/index.js
This PR is super trivial. The `<AreaList />` used to have as a clickable area an arrow button. Then, the clickable area changed to be everything and the arrow button should've changed to just a plain arrow icon: it didn't. This PR removes the button, leaving just the icon.
> fix: area-list component arrow button is now only an icon

- app/components/common/area-list/index.js
- app/components/common/switch/index.js
Another super trivial PR.
Before: switch color always displayed same colors.
Now: switch color toggles between green and white on value change.
> Fix: switch giving no feedback

- app/redux-modules/areas.js
This PR addresses the following issue:
- Fix area images not showing up, by dispatching set area image action always and depending if the area image exists update the path or download the image.
> fix: area image not showing pt. 2

- app/components/map/index.js
- Uses force render for clusters in Android too. This prevents markers shuffling position.
> fix: map-marker-shuffling

- app/components/settings/index.js
- app/components/setup/header/index.js
- app/components/setup/index.js
- app/containers/settings/index.js
- app/helpers/user.js
- app/locales/en.json
- app/locales/es.json
- app/locales/fr.json
- app/locales/id.json
- app/locales/pt.json
- New `helpers/user.js` that includes a check for unsafe logouts
- Adds logout warning on the settings page, noticing the user that if he proceeds he'll lose the unsaved reports and drafts.
> feat: add-data-loss-warning

- app/store.js
Order matters, swapping two words could fix a critical bug 🎉 
The offline middleware wasn't aware of the outbox actions after rehydrate until another action was dispatched, so when the app starts and it doesn't dispatch any other action the offline wouldn't start and the actions would remain there forever.
Now the middleware is applied first and all of the actions go through it, including the rehydrate one.
Reference: https://redux.js.org/api-reference/compose 
Key: `Composes functions from right to left.`
> Fix offline not starting after rehydrate

- app/components/settings/area-detail/alert-system/dataset-options/index.js
This PR address a silent bug, introduced in the sidebar redesign. PATCH updates were being done everytime the sidebar was closed.
> fix: dataset options date format
